// <auto-generated />
using System;
using CropSurvey.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CropSurvey.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220608080927_CropsSeed")]
    partial class CropsSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CropSurvey.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("GenderID")
                        .HasColumnType("int");

                    b.Property<int?>("KnowledgeLevelID")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("WantResults")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GenderID");

                    b.HasIndex("KnowledgeLevelID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CropSurvey.Model.Crop", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Timer")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("PhotoID");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            ID = "1x1_10594271873_611e07a39d_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "10594271873_611e07a39d_c.jpg",
                            Timer = 0.051065308999999996
                        },
                        new
                        {
                            ID = "1x1_13218800635_d1bf8dae11_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "13218800635_d1bf8dae11_c.jpg",
                            Timer = 0.033453663999999994
                        },
                        new
                        {
                            ID = "1x1_1636053650_4527b0585d_o_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "1636053650_4527b0585d_o.jpg",
                            Timer = 0.032287413000000001
                        },
                        new
                        {
                            ID = "1x1_16493328124_5facf01cba_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "16493328124_5facf01cba_c.jpg",
                            Timer = 0.023649838999999999
                        },
                        new
                        {
                            ID = "1x1_17107351976_7ca3d58d0c_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "17107351976_7ca3d58d0c_c.jpg",
                            Timer = 0.022672009999999999
                        },
                        new
                        {
                            ID = "1x1_18030243279_5e1d9c14cc_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "18030243279_5e1d9c14cc_c.jpg",
                            Timer = 0.031416159999999999
                        },
                        new
                        {
                            ID = "1x1_18421963655_2727ba7430_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "18421963655_2727ba7430_c.jpg",
                            Timer = 0.018862185
                        },
                        new
                        {
                            ID = "1x1_19538819028_1797fb1da6_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "19538819028_1797fb1da6_c.jpg",
                            Timer = 0.020661061999999997
                        },
                        new
                        {
                            ID = "1x1_2794729330_69101390e5_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "2794729330_69101390e5_b.jpg",
                            Timer = 0.045084736
                        },
                        new
                        {
                            ID = "1x1_4192603791_ef6a86762b_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "4192603791_ef6a86762b_b.jpg",
                            Timer = 0.049678398999999998
                        },
                        new
                        {
                            ID = "1x1_521658559_37f2907db4_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "521658559_37f2907db4_b.jpg",
                            Timer = 0.041453280999999995
                        },
                        new
                        {
                            ID = "1x1_5244375725_31bd21d487_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "5244375725_31bd21d487_b.jpg",
                            Timer = 0.047631633999999999
                        },
                        new
                        {
                            ID = "1x1_6060249948_51746b754f_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "6060249948_51746b754f_b.jpg",
                            Timer = 0.049271327999999996
                        },
                        new
                        {
                            ID = "1x1_8328219972_f44dd01091_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "8328219972_f44dd01091_c.jpg",
                            Timer = 0.023276989999999997
                        },
                        new
                        {
                            ID = "1x1_8698896427_3dc7d59b02_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "1x1",
                            PhotoID = "8698896427_3dc7d59b02_c.jpg",
                            Timer = 0.019415742999999999
                        },
                        new
                        {
                            ID = "9x16_10594271873_611e07a39d_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "10594271873_611e07a39d_c.jpg",
                            Timer = 0.073245668999999985
                        },
                        new
                        {
                            ID = "9x16_13218800635_d1bf8dae11_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "13218800635_d1bf8dae11_c.jpg",
                            Timer = 0.056396752999999994
                        },
                        new
                        {
                            ID = "9x16_1636053650_4527b0585d_o_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "1636053650_4527b0585d_o.jpg",
                            Timer = 0.063656571999999995
                        },
                        new
                        {
                            ID = "9x16_16493328124_5facf01cba_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "16493328124_5facf01cba_c.jpg",
                            Timer = 0.047859749
                        },
                        new
                        {
                            ID = "9x16_17107351976_7ca3d58d0c_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "17107351976_7ca3d58d0c_c.jpg",
                            Timer = 0.046578771999999997
                        },
                        new
                        {
                            ID = "9x16_18030243279_5e1d9c14cc_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "18030243279_5e1d9c14cc_c.jpg",
                            Timer = 0.059915217
                        },
                        new
                        {
                            ID = "9x16_18421963655_2727ba7430_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "18421963655_2727ba7430_c.jpg",
                            Timer = 0.049609460000000001
                        },
                        new
                        {
                            ID = "9x16_19538819028_1797fb1da6_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "19538819028_1797fb1da6_c.jpg",
                            Timer = 0.032801254000000002
                        },
                        new
                        {
                            ID = "9x16_2794729330_69101390e5_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "2794729330_69101390e5_b.jpg",
                            Timer = 0.078541163999999997
                        },
                        new
                        {
                            ID = "9x16_4192603791_ef6a86762b_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "4192603791_ef6a86762b_b.jpg",
                            Timer = 0.068450488999999989
                        },
                        new
                        {
                            ID = "9x16_521658559_37f2907db4_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "521658559_37f2907db4_b.jpg",
                            Timer = 0.064971199999999993
                        },
                        new
                        {
                            ID = "9x16_5244375725_31bd21d487_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "5244375725_31bd21d487_b.jpg",
                            Timer = 0.066298547999999999
                        },
                        new
                        {
                            ID = "9x16_6060249948_51746b754f_b_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "6060249948_51746b754f_b.jpg",
                            Timer = 0.067716222000000006
                        },
                        new
                        {
                            ID = "9x16_8328219972_f44dd01091_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "8328219972_f44dd01091_c.jpg",
                            Timer = 0.050234492999999998
                        },
                        new
                        {
                            ID = "9x16_8698896427_3dc7d59b02_c_SCJS.jpg",
                            Algorithm = "SCJS",
                            AspectRatio = "9x16",
                            PhotoID = "8698896427_3dc7d59b02_c.jpg",
                            Timer = 0.050233554999999992
                        },
                        new
                        {
                            ID = "1x1_8328219972_f44dd01091_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "8328219972_f44dd01091_c.jpg",
                            Timer = 0.239204
                        },
                        new
                        {
                            ID = "1x1_17107351976_7ca3d58d0c_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "17107351976_7ca3d58d0c_c.jpg",
                            Timer = 0.206625
                        },
                        new
                        {
                            ID = "1x1_1636053650_4527b0585d_o_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "1636053650_4527b0585d_o.jpg",
                            Timer = 0.16977200000000001
                        },
                        new
                        {
                            ID = "1x1_5244375725_31bd21d487_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "5244375725_31bd21d487_b.jpg",
                            Timer = 0.16248599999999999
                        },
                        new
                        {
                            ID = "1x1_19538819028_1797fb1da6_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "19538819028_1797fb1da6_c.jpg",
                            Timer = 0.16305700000000001
                        },
                        new
                        {
                            ID = "1x1_16493328124_5facf01cba_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "16493328124_5facf01cba_c.jpg",
                            Timer = 0.160915
                        },
                        new
                        {
                            ID = "1x1_2794729330_69101390e5_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "2794729330_69101390e5_b.jpg",
                            Timer = 0.18201999999999999
                        },
                        new
                        {
                            ID = "1x1_13218800635_d1bf8dae11_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "13218800635_d1bf8dae11_c.jpg",
                            Timer = 0.161137
                        },
                        new
                        {
                            ID = "1x1_18421963655_2727ba7430_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "18421963655_2727ba7430_c.jpg",
                            Timer = 0.163498
                        },
                        new
                        {
                            ID = "1x1_8698896427_3dc7d59b02_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "8698896427_3dc7d59b02_c.jpg",
                            Timer = 0.168237
                        },
                        new
                        {
                            ID = "1x1_10594271873_611e07a39d_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "10594271873_611e07a39d_c.jpg",
                            Timer = 0.17000399999999999
                        },
                        new
                        {
                            ID = "1x1_6060249948_51746b754f_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "6060249948_51746b754f_b.jpg",
                            Timer = 0.174479
                        },
                        new
                        {
                            ID = "1x1_18030243279_5e1d9c14cc_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "18030243279_5e1d9c14cc_c.jpg",
                            Timer = 0.185504
                        },
                        new
                        {
                            ID = "1x1_4192603791_ef6a86762b_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "4192603791_ef6a86762b_b.jpg",
                            Timer = 0.17005600000000001
                        },
                        new
                        {
                            ID = "1x1_521658559_37f2907db4_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "1x1",
                            PhotoID = "521658559_37f2907db4_b.jpg",
                            Timer = 0.166793
                        },
                        new
                        {
                            ID = "9x16_8328219972_f44dd01091_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "8328219972_f44dd01091_c.jpg",
                            Timer = 0.205904
                        },
                        new
                        {
                            ID = "9x16_17107351976_7ca3d58d0c_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "17107351976_7ca3d58d0c_c.jpg",
                            Timer = 0.19542599999999999
                        },
                        new
                        {
                            ID = "9x16_1636053650_4527b0585d_o_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "1636053650_4527b0585d_o.jpg",
                            Timer = 0.17463400000000001
                        },
                        new
                        {
                            ID = "9x16_5244375725_31bd21d487_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "5244375725_31bd21d487_b.jpg",
                            Timer = 0.17402100000000001
                        },
                        new
                        {
                            ID = "9x16_19538819028_1797fb1da6_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "19538819028_1797fb1da6_c.jpg",
                            Timer = 0.16321099999999999
                        },
                        new
                        {
                            ID = "9x16_16493328124_5facf01cba_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "16493328124_5facf01cba_c.jpg",
                            Timer = 0.16088
                        },
                        new
                        {
                            ID = "9x16_2794729330_69101390e5_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "2794729330_69101390e5_b.jpg",
                            Timer = 0.18517800000000001
                        },
                        new
                        {
                            ID = "9x16_13218800635_d1bf8dae11_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "13218800635_d1bf8dae11_c.jpg",
                            Timer = 0.170317
                        },
                        new
                        {
                            ID = "9x16_18421963655_2727ba7430_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "18421963655_2727ba7430_c.jpg",
                            Timer = 0.173683
                        },
                        new
                        {
                            ID = "9x16_8698896427_3dc7d59b02_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "8698896427_3dc7d59b02_c.jpg",
                            Timer = 0.17077899999999999
                        },
                        new
                        {
                            ID = "9x16_10594271873_611e07a39d_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "10594271873_611e07a39d_c.jpg",
                            Timer = 0.17738499999999999
                        },
                        new
                        {
                            ID = "9x16_6060249948_51746b754f_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "6060249948_51746b754f_b.jpg",
                            Timer = 0.168851
                        },
                        new
                        {
                            ID = "9x16_18030243279_5e1d9c14cc_c_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "18030243279_5e1d9c14cc_c.jpg",
                            Timer = 0.19206799999999999
                        },
                        new
                        {
                            ID = "9x16_4192603791_ef6a86762b_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "4192603791_ef6a86762b_b.jpg",
                            Timer = 0.173125
                        },
                        new
                        {
                            ID = "9x16_521658559_37f2907db4_b_GAIC.jpg",
                            Algorithm = "GAIC",
                            AspectRatio = "9x16",
                            PhotoID = "521658559_37f2907db4_b.jpg",
                            Timer = 0.17425199999999999
                        });
                });

            modelBuilder.Entity("CropSurvey.Model.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Muški"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ženski"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nije navedeno"
                        });
                });

            modelBuilder.Entity("CropSurvey.Model.KnowledgeLevel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KnowledgeLevels");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Nikakvo do osnovno"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Osnovno do srednje"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Srednje do napredno"
                        });
                });

            modelBuilder.Entity("CropSurvey.Model.Photo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            ID = "1636053650_4527b0585d_o.jpg",
                            CategoryID = 1
                        },
                        new
                        {
                            ID = "5244375725_31bd21d487_b.jpg",
                            CategoryID = 1
                        },
                        new
                        {
                            ID = "17107351976_7ca3d58d0c_c.jpg",
                            CategoryID = 1
                        },
                        new
                        {
                            ID = "18421963655_2727ba7430_c.jpg",
                            CategoryID = 1
                        },
                        new
                        {
                            ID = "19538819028_1797fb1da6_c.jpg",
                            CategoryID = 1
                        },
                        new
                        {
                            ID = "521658559_37f2907db4_b.jpg",
                            CategoryID = 2
                        },
                        new
                        {
                            ID = "2794729330_69101390e5_b.jpg",
                            CategoryID = 2
                        },
                        new
                        {
                            ID = "8698896427_3dc7d59b02_c.jpg",
                            CategoryID = 2
                        },
                        new
                        {
                            ID = "10594271873_611e07a39d_c.jpg",
                            CategoryID = 2
                        },
                        new
                        {
                            ID = "13218800635_d1bf8dae11_c.jpg",
                            CategoryID = 2
                        },
                        new
                        {
                            ID = "4192603791_ef6a86762b_b.jpg",
                            CategoryID = 3
                        },
                        new
                        {
                            ID = "6060249948_51746b754f_b.jpg",
                            CategoryID = 3
                        },
                        new
                        {
                            ID = "8328219972_f44dd01091_c.jpg",
                            CategoryID = 3
                        },
                        new
                        {
                            ID = "16493328124_5facf01cba_c.jpg",
                            CategoryID = 3
                        },
                        new
                        {
                            ID = "18030243279_5e1d9c14cc_c.jpg",
                            CategoryID = 3
                        });
                });

            modelBuilder.Entity("CropSurvey.Model.PhotoCategory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PhotoCategories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "one_subject"
                        },
                        new
                        {
                            ID = 2,
                            Name = "multiple_subjects"
                        },
                        new
                        {
                            ID = 3,
                            Name = "no_subject"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CropSurvey.Model.AppUser", b =>
                {
                    b.HasOne("CropSurvey.Model.Gender", "Gender")
                        .WithMany("Users")
                        .HasForeignKey("GenderID");

                    b.HasOne("CropSurvey.Model.KnowledgeLevel", "KnowledgeLevel")
                        .WithMany("Users")
                        .HasForeignKey("KnowledgeLevelID");

                    b.Navigation("Gender");

                    b.Navigation("KnowledgeLevel");
                });

            modelBuilder.Entity("CropSurvey.Model.Crop", b =>
                {
                    b.HasOne("CropSurvey.Model.Photo", "Photo")
                        .WithMany("Crops")
                        .HasForeignKey("PhotoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("CropSurvey.Model.Photo", b =>
                {
                    b.HasOne("CropSurvey.Model.PhotoCategory", "Category")
                        .WithMany("Photos")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CropSurvey.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CropSurvey.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CropSurvey.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CropSurvey.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CropSurvey.Model.Gender", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CropSurvey.Model.KnowledgeLevel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CropSurvey.Model.Photo", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("CropSurvey.Model.PhotoCategory", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
